version: '3.2'

volumes:
  data:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/secret_mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/secret_mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - secret_mysql_root_password
      - secret_mysql_password

  app:
    image: nextcloud:19.0.1-apache
    ports:
      - 8080:80
    volumes:
      - data:/var/www/html
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db:3306
      - MYSQL_PASSWORD_FILE=/run/secrets/secret_mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/secret_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/secret_admin_user
    secrets:
      - secret_mysql_password
      - secret_admin_user
      - secret_admin_password
    
secrets:
  secret_mysql_root_password:
    file: ./secret_mysql_root_password.txt
  secret_mysql_password:
    file: ./secret_mysql_password.txt
  secret_admin_user:
    file: ./secret_admin_user.txt
  secret_admin_password:
    file: ./secret_admin_password.txt
