version: '3'
services:
  hornet:
    build:
      context: .
      # For aarch64/arm64 use Dockerfile.arm64
      dockerfile: docker/Dockerfile
    image: hornet
    # Best performance via host network:
    network_mode: host
    # Else:
    #ports:
    #  - "14265:14265"
    #  - "15600:15600"
    cap_drop:
      - ALL
    
    volumes:
      - ./config.json:/app/config.json:ro
      - ./snapshots/mainnet:/app/snapshots/mainnet
      - ./mainnetdb:/app/mainnetdb
